### ISSUE TITLE
docker-compose up failing

### ISSUE THREAD

**Issue by jachym** [geopython/geopython-workshop#40]
Looks like `docker-compose up` (as called from `./geopython-workshop-ctl.sh start`) is failing, due to

```
geopython-workshop-pygeoapi | Traceback (most recent call last):
geopython-workshop-pygeoapi |   File "/usr/local/bin/pygeoapi", line 11, in <module>
geopython-workshop-pygeoapi |     load_entry_point('pygeoapi', 'console_scripts', 'pygeoapi')()
geopython-workshop-pygeoapi |   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
geopython-workshop-pygeoapi |     return self.main(*args, **kwargs)
geopython-workshop-pygeoapi |   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
geopython-workshop-pygeoapi |     rv = self.invoke(ctx)
geopython-workshop-pygeoapi |   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
geopython-workshop-pygeoapi |     return _process_result(sub_ctx.command.invoke(sub_ctx))
geopython-workshop-pygeoapi |   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
geopython-workshop-pygeoapi |     return ctx.invoke(self.callback, **ctx.params)
geopython-workshop-pygeoapi |   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
geopython-workshop-pygeoapi |     return callback(*args, **kwargs)
geopython-workshop-pygeoapi |   File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 17, in new_func
geopython-workshop-pygeoapi |     return f(get_current_context(), *args, **kwargs)
geopython-workshop-pygeoapi |   File "/pygeoapi/pygeoapi/openapi.py", line 519, in generate_openapi_document
geopython-workshop-pygeoapi |     click.echo(yaml.safe_dump(get_oas(s), default_flow_style=False))
geopython-workshop-pygeoapi |   File "/pygeoapi/pygeoapi/openapi.py", line 504, in get_oas
geopython-workshop-pygeoapi |     return get_oas_30(cfg)
geopython-workshop-pygeoapi |   File "/pygeoapi/pygeoapi/openapi.py", line 336, in get_oas_30
geopython-workshop-pygeoapi |     p = load_plugin('provider', cfg['datasets'][k]['provider'])
geopython-workshop-pygeoapi |   File "/pygeoapi/pygeoapi/plugin.py", line 82, in load_plugin
geopython-workshop-pygeoapi |     raise InvalidPluginError(msg)
geopython-workshop-pygeoapi | pygeoapi.plugin.InvalidPluginError: Plugin SQLite not found
```

**Comment by jachym** [comment]
And another one

```
geopython-workshop-jupyter | Traceback (most recent call last):
geopython-workshop-jupyter |   File "/usr/local/bin/jupyter", line 6, in <module>
geopython-workshop-jupyter |     from jupyter_core.command import main
geopython-workshop-jupyter |   File "/usr/local/lib/python3.7/dist-packages/jupyter_core/command.py", line 25, in <module>
geopython-workshop-jupyter |     from . import paths
geopython-workshop-jupyter |   File "/usr/local/lib/python3.7/dist-packages/jupyter_core/paths.py", line 21, in <module>
geopython-workshop-jupyter |     from distutils.util import strtobool
geopython-workshop-jupyter | ModuleNotFoundError: No module named 'distutils.util'
```

**Comment by justb4** [comment]
Hmm, the first is a `pygeoapi` issue, could be serious, though `latest` Docker Image is also running fine on demo: https://demo.pygeoapi.io/master. 

You could try a stable `pygeoapi` version like `0.7.0`. Think it is good to pin `pygeoapi and pycsw` versions anyway (i.s.o. `latest`) in the `compose` file. 

And you could try the [online Binder version](https://mybinder.org/v2/gh/geopython/geopython-workshop/master?filepath=workshop%2Fjupyter%2Fcontent%2Fnotebooks%2F01-introduction.ipynb).

**Comment by justb4** [comment]
Ok, the pygeoapi error is surely being its local config file here being out of date with `latest` version Docker image. The Binder version of the WS does not include pygeoapi. 
See https://github.com/geopython/geopython-workshop/blob/master/workshop/services/pygeoapi-config.yml#L172 , the countries dataset uses SQLite which is currently not supported due to deps problem. Commenting out that dataset will help, or replace by ogr provider.

**Comment by tomkralidis** [comment]
Works with latest master and pygeoapi configuration udpates.  @jachym feel free to re-open if you still have issues.
