### ISSUE TITLE
validate section 7

### ISSUE THREAD

**Issue by tomkralidis** [geopython/geopython-workshop#80]
@ldesousa reports that there are page load issues for section 7 (visualization).  We should validate/confirm and try to reproduce.

**Comment by justb4** [comment]
Interesting:

* when pulling the version from DockerHub I can run all Cells fine
* when I build locally, same version of the Notebook, some Cells working but also several failures

Think has to do with missing requirements. In the Dockerfile we use the latest versions for Ubuntu Focal so these have progressed. Errors below, but I think fixable.

Folium:

```
ttributeError                            Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import folium
      3 folium_map = folium.Map(location=[-34.603722, -58.381592])

File /usr/local/lib/python3.8/dist-packages/folium/__init__.py:5, in <module>
      1 # -*- coding: utf-8 -*-
      3 import sys
----> 5 import branca
      6 from branca.colormap import (ColorMap, LinearColormap, StepColormap)
      7 from branca.element import (
      8     CssLink,
      9     Div,
   (...)
     16     MacroElement,
     17 )

File /usr/local/lib/python3.8/dist-packages/branca/__init__.py:1, in <module>
----> 1 import branca.colormap as colormap
      2 import branca.element as element
      4 from ._version import get_versions

File /usr/local/lib/python3.8/dist-packages/branca/colormap.py:15, in <module>
     11 import os
     13 from jinja2 import Template
---> 15 from branca.element import ENV, Figure, JavascriptLink, MacroElement
     16 from branca.utilities import legend_scaler
     18 rootpath = os.path.abspath(os.path.dirname(__file__))

File /usr/local/lib/python3.8/dist-packages/branca/element.py:21, in <module>
     17 from pathlib import Path
     19 from jinja2 import Environment, PackageLoader, Template
---> 21 from .utilities import _camelify, _parse_size, none_max, none_min
     23 ENV = Environment(loader=PackageLoader('branca', 'templates'))
     26 class Element(object):

File /usr/local/lib/python3.8/dist-packages/branca/utilities.py:19, in <module>
     16 from jinja2 import Environment, PackageLoader
     18 try:
---> 19     import pandas as pd
     20 except ImportError:
     21     pd = None

File /usr/local/lib/python3.8/dist-packages/pandas/__init__.py:22, in <module>
     19 del hard_dependencies, dependency, missing_dependencies
     21 # numpy compat
---> 22 from pandas.compat import is_numpy_dev as _is_numpy_dev
     24 try:
     25     from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib

File /usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py:14, in <module>
     11 import platform
     12 import sys
---> 14 from pandas._typing import F
```

And in Bokeh:

```
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/util/dependencies.py", line 53, in import_optional
    return import_module(mod_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py", line 14, in <module>
    from pandas._typing import F
  File "/usr/local/lib/python3.8/dist-packages/pandas/_typing.py", line 120, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/util/dependencies.py", line 53, in import_optional
    return import_module(mod_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py", line 14, in <module>
    from pandas._typing import F
  File "/usr/local/lib/python3.8/dist-packages/pandas/_typing.py", line 120, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/util/dependencies.py", line 53, in import_optional
    return import_module(mod_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py", line 14, in <module>
    from pandas._typing import F
  File "/usr/local/lib/python3.8/dist-packages/pandas/_typing.py", line 120, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/util/dependencies.py", line 53, in import_optional
    return import_module(mod_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py", line 14, in <module>
    from pandas._typing import F
  File "/usr/local/lib/python3.8/dist-packages/pandas/_typing.py", line 120, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/util/dependencies.py", line 53, in import_optional
    return import_module(mod_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py", line 14, in <module>
    from pandas._typing import F
  File "/usr/local/lib/python3.8/dist-packages/pandas/_typing.py", line 120, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/util/dependencies.py", line 53, in import_optional
    return import_module(mod_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py", line 14, in <module>
    from pandas._typing import F
  File "/usr/local/lib/python3.8/dist-packages/pandas/_typing.py", line 120, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/util/dependencies.py", line 53, in import_optional
    return import_module(mod_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py", line 14, in <module>
    from pandas._typing import F
  File "/usr/local/lib/python3.8/dist-packages/pandas/_typing.py", line 120, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/util/dependencies.py", line 53, in import_optional
    return import_module(mod_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py", line 14, in <module>
    from pandas._typing import F
  File "/usr/local/lib/python3.8/dist-packages/pandas/_typing.py", line 120, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'
ERROR:bokeh.util.dependencies:Failed to import optional module `pandas`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/util/dependencies.py", line 53, in import_optional
    return import_module(mod_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py", line 14, in <module>
    from pandas._typing import F
  File "/usr/local/lib/python3.8/dist-packages/pandas/_typing.py", line 120, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'
```
And
```
AttributeError                            Traceback (most recent call last)
Input In [13], in <cell line: 1>()
----> 1 import geopandas as gpd
      3 # Read the data (already in Web Mercator projection (ignore the warning)
      4 points = gpd.read_file('../data/populated_places.3857.gpkg')

File /usr/local/lib/python3.8/dist-packages/geopandas/__init__.py:1, in <module>
----> 1 from geopandas._config import options  # noqa
      3 from geopandas.geoseries import GeoSeries  # noqa
      4 from geopandas.geodataframe import GeoDataFrame  # noqa
```

**Comment by justb4** [comment]
Think the problem is a mismatch between Python packages installed via Debian `python-*` packages in `/usr/lib/python3` and those installed via pip in `/usr/local/lib`. e.g. numpy has 1.17 in /usr/lib and 1.23 when installing via pip in /usr/local....will try upgrade to Ubuntu Jammy first (22.04).

**Comment by justb4** [comment]
Upgrading to Jammy, I think is necessary, introduced quite some challenges, especially for Proj/pyproj. After quite some build failures (wheels) etc. I managed to build the Docker Image again. And guess: all Cells in chapter 7 were working! But...now getting error from 3 (Projections), something with Shapely.

But now I get an error in Ch3 Projections:

![image](https://user-images.githubusercontent.com/582630/183287948-ab7ef566-c665-4687-800a-d1539c28ee00.png)

**Comment by justb4** [comment]
Think the above is a type error but this works:
```
import shapely.wkt

borders = shapely.wkt.loads(feature.GetGeometryRef().ExportToWkt())
```
i.s.o.
`borders = shapely.wkb.loads(feature.GetGeometryRef().ExportToWkb())` 
or need to fiddle with `bytearray`.

**Comment by francbartoli** [comment]
it's ok for me

**Comment by krishnaglodha** [comment]
It's not working for me too :(

**Comment by krishnaglodha** [comment]
updating docker solved the issue :)

**Comment by justb4** [comment]
so we can close?
